package com.cometproject.server.protocol.headers;


import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.HashMap;
import java.util.Map;


public class Events {
    public static final short ConfirmUsernameMessageEvent = 3199;
    public static final short GetRoomBannedUsersMessageEvent = 824;
    public static final short GetPetInventoryMessageEvent = 2326;
    public static final short DropHandItemMessageEvent = 1454;
    public static final short ReleaseTicketMessageEvent = 893;
    public static final short GetModeratorRoomInfoMessageEvent = 1701;
    public static final short KickUserMessageEvent = 310;
    public static final short SaveWiredEffectConfigMessageEvent = 3789;
    public static final short RespectPetMessageEvent = 856;
    public static final short GenerateSecretKeyMessageEvent = 1127;
    public static final short GetModeratorTicketChatlogsMessageEvent = 1660;
    public static final short GetAchievementsMessageEvent = 1039;
    public static final short SaveWiredTriggerConfigMessageEvent = 2954;
    public static final short AcceptGroupMembershipMessageEvent = 3155;
    public static final short GetGroupFurniSettingsMessageEvent = 1123;
    public static final short TakeAdminRightsMessageEvent = 3630;
    public static final short RemoveAllRightsMessageEvent = 2853;
    public static final short UpdateThreadMessageEvent = 1911;
    public static final short ManageGroupMessageEvent = 1992;
    public static final short ModifyRoomFilterListMessageEvent = 514;
    public static final short SSOTicketMessageEvent = 2190;
    public static final short JoinGroupMessageEvent = 887;
    public static final short DeclineGroupMembershipMessageEvent = 40;
    public static final short UniqueIDMessageEvent = 522;
    public static final short RemoveMyRightsMessageEvent = 3765;
    public static final short ApplyHorseEffectMessageEvent = 1869;
    public static final short GetPetInformationMessageEvent = 2517;
    public static final short GiveHandItemMessageEvent = 881;
    public static final short UpdateFigureDataMessageEvent = 586;
    public static final short RemoveGroupMemberMessageEvent = 2541;
    public static final short EventLogMessageEvent = 1252;
    public static final short RefreshCampaignMessageEvent = 1409;
    public static final short GetPromotableRoomsMessageEvent = 381;
    public static final short UseOneWayGateMessageEvent = 1136;
    public static final short AddStickyNoteMessageEvent = 1554;
    public static final short GetSelectedBadgesMessageEvent = 3562;
    public static final short UpdateStickyNoteMessageEvent = 1858;
    public static final short CloseTicketMesageEvent = 78;
    public static final short RequestBuddyMessageEvent = 918;
    public static final short GetFurnitureAliasesMessageEvent = 2437;
    public static final short GetRoomSettingsMessageEvent = 501;
    public static final short RequestFurniInventoryMessageEvent = 2905;
    public static final short ModerationKickMessageEvent = 933;
    public static final short OpenFlatConnectionMessageEvent = 1718;
    public static final short DanceMessageEvent = 1527;
    public static final short RemoveBuddyMessageEvent = 3022;
    public static final short LatencyTestMessageEvent = 3978;
    public static final short InfoRetrieveMessageEvent = 518;
    public static final short YouTubeGetNextVideo = 1202;
    public static final short SetObjectDataMessageEvent = 1429;
    public static final short MessengerInitMessageEvent = 958;
    public static final short PickUpBotMessageEvent = 2790;
    public static final short ActionMessageEvent = 2234;
    public static final short LookToMessageEvent = 2187;
    public static final short ToggleMoodlightMessageEvent = 3440;
    public static final short FollowFriendMessageEvent = 2087;
    public static final short PickUpPetMessageEvent = 814;
    public static final short GetSellablePetBreedsMessageEvent = 2463;
    public static final short GetForumUserProfileMessageEvent = 1279;
    public static final short GetForumsListDataMessageEvent = 1307;
    public static final short IgnoreUserMessageEvent = 2825;
    public static final short DeleteRoomMessageEvent = 1748;
    public static final short StartQuestMessageEvent = 646;
    public static final short GetGiftWrappingConfigurationMessageEvent = 1400;
    public static final short UpdateGroupIdentityMessageEvent = 3296;
    public static final short RideHorseMessageEvent = 3097;
    public static final short ApplySignMessageEvent = 619;
    public static final short FindRandomFriendingRoomMessageEvent = 2960;
    public static final short GetModeratorUserChatlogMessageEvent = 1655;
    public static final short GetWardrobeMessageEvent = 3046;
    public static final short MuteUserMessageEvent = 431;
    public static final short UpdateForumSettingsMessageEvent = 663;
    public static final short ApplyDecorationMessageEvent = 368;
    public static final short GetBotInventoryMessageEvent = 1621;
    public static final short UseHabboWheelMessageEvent = 1152;
    public static final short EditRoomPromotionMessageEvent = 643;
    public static final short GetModeratorUserInfoMessageEvent = 2821;
    public static final short PlaceBotMessageEvent = 2833;
    public static final short GetCatalogPageMessageEvent = 3269;
    public static final short GetThreadsListDataMessageEvent = 3055;
    public static final short ShoutMessageEvent = 592;
    public static final short DiceOffMessageEvent = 2000;
    public static final short LetUserInMessageEvent = 3626;
    public static final short SetActivatedBadgesMessageEvent = 2581;
    public static final short UpdateGroupSettingsMessageEvent = 2123;
    public static final short ApproveNameMessageEvent = 750;
    public static final short SubmitNewTicketMessageEvent = 3736;
    public static final short DeleteGroupMessageEvent = 2962;
    public static final short DeleteStickyNoteMessageEvent = 2682;
    public static final short GetGroupInfoMessageEvent = 1850;
    public static final short GetStickyNoteMessageEvent = 2867;
    public static final short DeclineBuddyMessageEvent = 117;
    public static final short OpenGiftMessageEvent = 1575;
    public static final short GiveRoomScoreMessageEvent = 1327;
    public static final short SetGroupFavouriteMessageEvent = 486;
    public static final short SetMannequinNameMessageEvent = 2751;
    public static final short CallForHelpMessageEvent = 3736;
    public static final short RoomDimmerSavePresetMessageEvent = 445;
    public static final short UpdateGroupBadgeMessageEvent = 1690;
    public static final short PickTicketMessageEvent = 3975;
    public static final short SetTonerMessageEvent = 866;
    public static final short RespectUserMessageEvent = 2050;
    public static final short DeleteGroupThreadMessageEvent = 128;
    public static final short DeleteGroupReplyMessageEvent = 1198;
    public static final short CreditFurniRedeemMessageEvent = 946;
    public static final short ModerationMsgMessageEvent = 2828;
    public static final short ToggleYouTubeVideoMessageEvent = 1293;
    public static final short UpdateNavigatorSettingsMessageEvent = 2178;
    public static final short ToggleMuteToolMessageEvent = 3553;
    public static final short ChatMessageEvent = 395;
    public static final short SaveRoomSettingsMessageEvent = 1732;
    public static final short PurchaseFromCatalogAsGiftMessageEvent = 2678;
    public static final short GetGroupCreationWindowMessageEvent = 807;
    public static final short GiveAdminRightsMessageEvent = 3221;
    public static final short GetGroupMembersMessageEvent = 1834;
    public static final short ModerateRoomMessageEvent = 64;
    public static final short GetForumStatsMessageEvent = 952;
    public static final short GetPromoArticlesMessageEvent = 1090;
    public static final short SitMessageEvent = 1250;
    public static final short SetSoundSettingsMessageEvent = 1266;
    public static final short ModerationCautionMessageEvent = 3585;
    public static final short InitializeFloorPlanSessionMessageEvent = 228;
    public static final short ModeratorActionMessageEvent = 1282;
    public static final short PostGroupContentMessageEvent = 147;
    public static final short GetModeratorRoomChatlogMessageEvent = 3136;
    public static final short GetUserFlatCatsMessageEvent = 1832;
    public static final short RemoveRightsMessageEvent = 973;
    public static final short ModerationBanMessageEvent = 872;
    public static final short CanCreateRoomMessageEvent = 3014;
    public static final short UseWallItemMessageEvent = 3473;
    public static final short PlaceObjectMessageEvent = 2973;
    public static final short OpenBotActionMessageEvent = 901;
    public static final short GetEventCategoriesMessageEvent = 3783;
    public static final short GetRoomEntryDataMessageEvent = 227;
    public static final short MoveWallItemMessageEvent = 3094;
    public static final short UpdateGroupColoursMessageEvent = 3125;
    public static final short HabboSearchMessageEvent = 3584;
    public static final short CommandBotMessageEvent = 3554;
    public static final short SetCustomStackingHeightMessageEvent = 3920;
    public static final short UnIgnoreUserMessageEvent = 101;
    public static final short GetGuestRoomMessageEvent = 552;
    public static final short SetMannequinFigureMessageEvent = 2975;
    public static final short AssignRightsMessageEvent = 1917;
    public static final short GetYouTubeTelevisionMessageEvent = 1443;
    public static final short SetMessengerInviteStatusMessageEvent = 625;
    public static final short UpdateFloorPropertiesMessageEvent = 2141;
    public static final short GetMoodlightConfigMessageEvent = 749;
    public static final short PurchaseRoomPromotionMessageEvent = 1403;
    public static final short SendRoomInviteMessageEvent = 1777;
    public static final short ModerationMuteMessageEvent = 3579;
    public static final short SetRelationshipMessageEvent = 1205;
    public static final short ChangeMottoMessageEvent = 1076;
    public static final short UnbanUserFromRoomMessageEvent = 3047;
    public static final short GetRoomRightsMessageEvent = 2683;
    public static final short PurchaseGroupMessageEvent = 3782;
    public static final short CreateFlatMessageEvent = 2139;
    public static final short OpenHelpToolMessageEvent = 924;
    public static final short ThrowDiceMessageEvent = 1886;
    public static final short SaveWiredConditionConfigMessageEvent = 676;
    public static final short GetCatalogOfferMessageEvent = 1181;
    public static final short PurchaseFromCatalogMessageEvent = 1733;
    public static final short PickupObjectMessageEvent = 1504;
    public static final short CancelQuestMessageEvent = 2672;
    public static final short NavigatorSearchMessageEvent = 3706;
    public static final short MoveAvatarMessageEvent = 2175;
    public static final short GetClientVersionMessageEvent = 4000;
    public static final short InitializeNavigatorMessageEvent = 2061;
    public static final short GetRoomFilterListMessageEvent = 354;
    public static final short WhisperMessageEvent = 3182;
    public static final short InitCryptoMessageEvent = 1905;
    public static final short GetPetTrainingPanelMessageEvent = 3274;
    public static final short MoveObjectMessageEvent = 2104;
    public static final short StartTypingMessageEvent = 1147;
    public static final short GoToHotelViewMessageEvent = 882;
    public static final short GetExtendedProfileMessageEvent = 3596;
    public static final short SendMsgMessageEvent = 779;
    public static final short CancelTypingMessageEvent = 2045;
    public static final short GetGroupFurniConfigMessageEvent = 38;
    public static final short RemoveGroupFavouriteMessageEvent = 73;
    public static final short PlacePetMessageEvent = 3332;
    public static final short ModifyWhoCanRideHorseMessageEvent = 921;
    public static final short GetRelationshipsMessageEvent = 2220;
    public static final short GetCatalogIndexMessageEvent = 3285;
    public static final short ScrGetUserInfoMessageEvent = 2657;
    public static final short ConfirmLoveLockMessageEvent = 3256;
    public static final short RemoveSaddleFromHorseMessageEvent = 3853;
    public static final short AcceptBuddyMessageEvent = 661;
    public static final short GetQuestListMessageEvent = 46;
    public static final short SaveWardrobeOutfitMessageEvent = 596;
    public static final short BanUserMessageEvent = 3344;
    public static final short GetThreadDataMessageEvent = 2335;
    public static final short GetBadgesMessageEvent = 916;
    public static final short UseFurnitureMessageEvent = 3119;
    public static final short GoToFlatMessageEvent = 3021;
    public static final short GetModeratorUserRoomVisitsMessageEvent = 757;
    public static final short GetSanctionStatusMessageEvent = 25;
    public static final short SetChatPreferenceMessageEvent = 3027;
    public static final short ResizeNavigatorMessageEvent = 3831;
    public static final short CameraDataMessageEvent = 782;
    public static final short RenderRoomMessageEvent = 2505;
    public static final short BuyPhotoMessageEvent = 2358;
    public static final short SongInventoryMessageEvent = 2675;
    public static final short SongIdMessageEvent = 2365;
    public static final short SongDataMessageEvent = 217;
    public static final short PlaylistMessageEvent = 3730;
    public static final short PlaylistAddMessageEvent = 2370;
    public static final short PlaylistRemoveMessageEvent = 3670;
    public static final short StaffPickRoomMessageEvent = 570;
    public static final short SubmitPollAnswerMessageEvent = 1762;
    public static final short GetPollMessageEvent = 405;
    public static final short UpdateSnapshotsMessageEvent = 2489;
    public static final short MarkAsReadMessageEvent = 3561;
    public static final short InitTradeMessageEvent = 2460;
    public static final short TradingOfferItemMessageEvent = 2849;
    public static final short TradingOfferItemsMessageEvent = 1884;
    public static final short TradingRemoveItemMessageEvent = 3227;
    public static final short TradingAcceptMessageEvent = 305;
    public static final short TradingCancelMessageEvent = 3003;
    public static final short TradingModifyMessageEvent = 3885;
    public static final short TradingConfirmMessageEvent = 620;
    public static final short TradingCancelConfirmMessageEvent = 3698;
    public static final short RedeemVoucherMessageEvent = 3327;
    public static final short Hide = 3327;
    public static final short ChangeNameMessageEvent = 2443;
    public static final short CheckValidNameMessageEvent = 2102;
    public static final short RequestGuideToolMessageEvent = 493;
    public static final short RequestGuideAssistanceMessageEvent = 330;
    public static final short GuideUserTypingMessageEvent = 186;
    public static final short GuideReportHelperMessageEvent = 1887;
    public static final short GuideRecommendHelperMessageEvent = 3350;
    public static final short GuideUserMessageMessageEvent = 479;
    public static final short GuideCancelHelpRequestMessageEvent = 2735;
    public static final short GuideHandleHelpRequestMessageEvent = 3827;
    public static final short GuideVisitUserMessageEvent = 1781;
    public static final short GuideInviteUserMessageEvent = 149;
    public static final short GuideCloseHelpRequestMessageEvent = 1626;
    public static final short GuardianNoUpdatesWantedMessageEvent = 2115;
    public static final short GuardianVoteMessageEvent = 1676;
    public static final short GuardianAcceptRequestMessageEvent = 3429;
    public static final short RequestReportUserBullyingMessageEvent = 2388;
    public static final short ReportBullyMessageEvent = 3543;
    public static final short GetUserTagsMessageEvent = 702;
    public static final short FindNewFriendsMessageEvent = 531;
    public static final short SaveNavigatorSearchMessageEvent = 3718;
    public static final short DeleteNavigatorSavedSearchMessageEvent = 1800;
    public static final short AddFavouriteRoomMessageEvent = 533;
    public static final short DeleteFavouriteRoomMessageEvent = 1160;
    public static final short SaveFootballGateMessageEvent = 3832;
    public static final short GroupConfirmRemoveMemberMessageEvent = 3478;
    public static final short GetGroupPartsMessageEvent = 2451;
    public static final short SetRoomCameraFollowMessageEvent = 3279;
    public static final short BreedPetsMessageEvent = 2805;


    private static Map<Short, String> eventPacketNames = new HashMap<>();

    static {
        try {
            for (Field field : Events.class.getDeclaredFields()) {
                if (!Modifier.isPrivate(field.getModifiers()))
                    eventPacketNames.put(field.getShort(field.getName()), field.getName());
            }
        } catch (Exception ignored) {

        }
    }

    public static String valueOfId(short packetId) {
        if (eventPacketNames.containsKey(packetId)) {
            return eventPacketNames.get(packetId);
        }

        return "UnknownMessageEvent";
    }
}